yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/', views.self_profile, name='self_profile'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Group title',
        help_text='Название группы',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Slug',
        help_text='Слаг Группы',
    )
    description = models.TextField(
        verbose_name='Description',
        help_text='Описание группы',
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Text Post',
        help_text='Текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='publication of date',
        help_text='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Author',
        help_text='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text='Группа поста',
        related_name='posts',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField(
        verbose_name='Text comment',
        help_text='Текст комментария',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Author',
        help_text='Автор',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='publication of date',
        help_text='Дата публикации',
    )

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                name='user_author_pair_unique',
                fields=['user', 'author'],
            ),
        ]

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Post, Comment

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        Widget = {
            'text': forms.Textarea(attrs={'class': 'form-input', }),
            'group': forms.ChoiceField(required=False, )
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post
from .utils import paginate_page


@cache_page(20)
def index(request):
    page_obj = paginate_page(request, Post.objects.all())
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_obj = paginate_page(request, group.posts.all())
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context=context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    page_obj = paginate_page(request, author.posts.all())
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author
    ).exists()
    context = {
        'following': following,
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    comment_form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'form': comment_form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):

    post = get_object_or_404(Post, id=post_id)

    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        post.save()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'is_edit': True,
        'post_id': post_id
    }

    return render(request, 'posts/create_post.html', context)


def self_profile(request):
    return redirect('posts:profile', request.user.username)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    page_obj = paginate_page(
        request, Post.objects.filter(author__following__user=request.user)
    )
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context=context)


@login_required
def profile_follow(request, username):
    if request.user.username == username or Follow.objects.filter(
            author__username=username,
            user=request.user).exists():
        return redirect('posts:index')

    Follow.objects.create(
        author=User.objects.get(username=username),
        user=request.user,
    )
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user, author__username=username
    ).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text | addclass:'form-control' }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text | linebreaksbr }}
      </p>
      <p>
        <b> {{ comment.created }} </b>
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    {% if is_edit %}
        Редактировать пост
    {% else %}
        Новый пост
    {% endif %}
{% endblock %}
{% block context %}

<form action="
{% if is_edit %}
    {% url 'posts:post_edit' post_id %}
{% else %}
    {% url 'posts:post_create' %}
{% endif %}
    " method="post" enctype="multipart/form-data">
{% csrf_token %}
{% for field in form  %}
    <p>
    {{ field.name }}
    {{ field }}
    </p>
{% endfor %}
<button type="submit" class="btn btn-primary">
    {% if is_edit %}
      Сохранить изменения
    {% else %}
      Добавить
    {% endif %}               
  </button> 
  
</form>

{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}

{% endblock title %}

{% block context %}
    <h1> Избранные авторы </h1>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
    <article>
    <ul>
        <li>
            Автор: {{ post.author }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date | date:"d E Y" }}
        </li>
    </ul>
    </article>
    <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {{ post.text | linebreaksbr }}
    </p>
    <p>
        <a href="{% url 'posts:post_detail' post.id %}">Детали</a>
    </p>
    {% if post.group.slug %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %} <hr> {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block context %}
    <h1> {{ group.title }} </h1>
    <p> {{ group.description | linebreaksbr }} </p>
    {% for post in page_obj %}
    <article>
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
            
        </li>
        <li>
            Дата публикации: {{ post.pub_date | date:"d E Y" }}
        </li>
    </ul>
    </article>
    <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {{ post.text | linebreaksbr }}
    </p>
    {% if not forloop.last %} <hr> {% endif %}

    {% endfor %}

    {% include 'includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Последние обновления на сайте
{% endblock title %}

{% block context %}
    <h1> Последние обновления на сайте </h1>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
    <article>
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date | date:"d E Y" }}
        </li>
    </ul>
    </article>
    <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {{ post.text | linebreaksbr }}
    </p>
    <p>
    <a href="{% url 'posts:post_detail' post.id %}">Детали</a>
    </p>
    {% if post.group.slug %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %} <hr> {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block title %}Пост {{ post.text | truncatechars:30 }}... {% endblock title %}
{% block context %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date | date:"SHORT_DATE_FORMAT"}} 
            </li>
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <li class="list-group-item">
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
              </li>
            </li>
              {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span> {{ post.author.posts.count }}  </span>
            </li>
            <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            {% if post.author == user %}
            <li class="list-group-item">
                <a href="{% url 'posts:post_edit' post.id %}">Решительно редактировать</a>
            </li>
            {% endif %}
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            {{ post.text | linebreaksbr}}
          </p>
        </article>
    {% include 'posts/comment.html' %}
{% endblock context %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Профайл пользователя {{ author }}
{% endblock title %}

{% block context %}
    <h1>Все посты пользователя {{ author }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>   
    {% if author != request.user %}
        {% if following %}
        <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
            Отписаться
        </a>
        {% else %}
        <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
            Подписаться
        </a>
        {% endif %}
    {% endif %}
{% for post in page_obj %}
<article>
<ul>
    <li>
        Автор: {{ author }}
        <a href="{% url 'posts:profile' author %}">все посты пользователя</a>
    </li>
    <li>
        Дата публикации: {{ post.pub_date }}
    </li>
    </ul>
    <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {{ post.text | linebreaksbr }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>

    <br>
    {% if post.group.slug %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a></article>       
    {% endif %}
    {% if not forloop.last %} <hr> {% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}